### ISSUE TITLE
Edit/View mode for Active/Past visit : Diagnoses fragment

### ISSUE THREAD

**Issue by DiyaIT1** [Intelehealth/intelehealth-openmrs-module#27]

**Comment by nehagoel2** [comment]
The diagnosis fragment does not show the entered diagnoses for a closed visit.

**Comment by nehagoel2** [comment]
![image](https://user-images.githubusercontent.com/14187848/29362212-9fe67a36-82a8-11e7-8a23-d5f12d636049.png)

For this patient, a diagnosis of "cough" and "fever of unknown origin" was added.

**Comment by prithi69** [comment]
in the patient overview screen "back to top" is not working.

**Comment by amalafrozalam** [comment]
@hardikk08 
Check src > webapp > resources > scripts > diagnoses > diagnoses.js

**Comment by amalafrozalam** [comment]
Above comment is incorrect. It's definitely in that file, but somewhere further along. 

The fragment seems to be saving the information correct, but it does not seem to be retrieving it correctly. Perhaps the URL call in one of the factories is incorrect. Specifically, when the page is loaded and previous/prior diagnoses are searched for.

**Comment by nehagoel2** [comment]
@amal - No code was written to retrieve and display diagnoses. It's not a bug. This was just not completed.

**Comment by amalafrozalam** [comment]
@nehagoel2 you tagged the wrong amal. Need to use my full username.

Okay, well that explains it. There _is_ a retrieval of sorts going on, but I believe that issues #23 and #44 are all related.

**Comment by hardikk08** [comment]
@nehagoel2 I wish you had pointed that out earlier @amalafrozalam I can see it being posted in the database. So basically the code to retrieve it is missing. Would have been easy if we knew the logic flow of the entire module hence it is taking time to understand. 
![screenshot 83](https://user-images.githubusercontent.com/29514954/33592018-d672b620-d9ae-11e7-93af-da2b79f6e31f.png)

**Comment by nehagoel2** [comment]
Look at closed issue #26

**Comment by nehagoel2** [comment]
https://github.com/openmrs/openmrs-module-coreapps/tree/master/omod/src/main/webapp/fragments/diagnosis

**Comment by nehagoel2** [comment]
https://github.com/openmrs/openmrs-module-coreapps/blob/master/omod/src/main/java/org/openmrs/module/coreapps/fragment/controller/DiagnosesFragmentController.java

**Comment by hardikk08** [comment]
I tried replicating the openmrs diagnosis code but obs is not being created and also the selected value is not being displayed!

**Comment by nehav39** [comment]
@hardikk08 - great job so far on the fragment. Just a last push:
1. For a closed visit, the text entry box for entering diagnosis should be hidden so that no new diagnoses can be entered
2. The diagnoses being seen in the Previous diagnoses are not marked as Primary, Secondary, Confirmed or Unconfirmed. These should also be seen
3. Previous diagnosis heading is in Red - make it consistent in look and feel.

**Comment by hardikk08** [comment]
For the 2nd point... 
This is a bit difficult to achieve, saying it after trying a lot of stuff and this feature will take time. Reason, obs for diagnoses is being posted just after we enter a diagnoses name hence clicking on primary or confirmed has no effect on what is being posted in the database! Hence the checkbox implementation is more of a dummy right now. The way it is happening in core apps is very complex and will require a lot of modification in our app.
