### ISSUE TITLE
Encounter Provider not being posted when posting an encounter.

### ISSUE THREAD

**Issue by dbarretto** [Intelehealth/intelehealth-openmrs-module#28]
Add this Array to your encounter POST request payload:

"encounterProviders":[{"encounterRole":"<encounter_role_uuid>",
                                "provider":"<provider_uuid>"}]

You can find all encounter roles by sending a GET request at {base_url}/encounterrole

I believe that you will be posting as Doctor so use this <encounter_role_uuid> "73bbb069-9781-4afc-a9d1-54b6b2270e03".

To get <provider_uuid> you will have to send a GET request at {base_url}/provider?user=<user_uuid>

For <user_uuid> sent a GET request to the <base_url>/session API
<img width="1129" alt="screen shot 2017-08-11 at 8 11 03 am" src="https://user-images.githubusercontent.com/28301176/29199733-f0acd072-7e6c-11e7-917a-6471449671d9.png">

**Comment by amalafrozalam** [comment]
@nehagoel2 is this an android thing or an OpenMRS thing?

**Comment by amalafrozalam** [comment]
Steps to take:
Let <base> = IPADDRESS:8080/openmrs/ws/rest/v1/
1. GET call to <base>/session
2. The response will contain information about the current user logged in.

From there, extract out the userUUID.
You will use that for the provider field in the JSON, as the query that @dbarretto suggested does not appear to work.

This needs to be added to the payload:

encounterProviders: [
    {
      provider: <user_UUID>,
      encounterRole: 73bbb069-9781-4afc-a9d1-54b6b2270e03
    }
]

**Comment by amalafrozalam** [comment]
A better way to do this would be to GET the encounter roles first, determine which is a doctor, then use that UUID. Implement that next after this is tested.

**Comment by amalafrozalam** [comment]
@hardikk08 can you implement these changes? Every time I try to implement a change, I somehow end up breaking all the UI elements. I think you might understand angular better than I do at the moment.

**Comment by hardikk08** [comment]
Current status - It was a pain to extract the uuid from the factory, had to work around promises. Now the moment I enter any thing into the JSON payload in patient summary factory, the encounter doesnt gets posted. @amalafrozalam If you can test the latest commit and see whats happening?

**Comment by hardikk08** [comment]
@amalafrozalam @prithi69 @nehagoel2 Have fixed the issue, provider is now being posted, can someone test this and let me know how it goes?

**Comment by prithi69** [comment]
Encounter provided being posted with a single encounter, tested. From the OpenMRS side it got finished, from the android side, its still left.
