### ISSUE TITLE
Replace hardcoded uuids with relevant constants and add them to constants or properties file

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/intelehealth-openmrs-module#30]

**Comment by nehagoel2** [comment]
Two uuids in the database are same

maitree.kuria
163205  67a050c1-35e5-451c-a4ab-fff9d57b0db1
163216  0308000d-77a2-46e0-a6fa-a8c1dcbc3141
Medical Advice

Which one needs to be posted to the app?

**Comment by prithi69** [comment]
163205 67a050c1-35e5-451c-a4ab-fff9d57b0db1..
This UUID needs to be posted in the app.
