### ISSUE TITLE
Allergy UI links to the clinician facing patient dashboard

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/intelehealth-openmrs-module#39]
IH patient dashboard > Allergy fragment links to clinician facing patient dashboard.

**Comment by nehagoel2** [comment]
Override returnUrl

https://github.com/openmrs/openmrs-module-allergyui/blob/master/omod/src/main/webapp/pages/allergies.gsp

**Comment by nehagoel2** [comment]
https://stackoverflow.com/questions/12008908/angularjs-how-can-i-pass-variables-between-controllers

**Comment by hardikk08** [comment]
http://localhost:8081/openmrs/admin/maintenance/globalProps.form

**Comment by hardikk08** [comment]
This issue was moved to Intelehealth/intelehealth-openmrs-ui#11
