### ISSUE TITLE
Hyperlink for Doctor's Note not working on Patient Overview screen

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/intelehealth-openmrs-module#54]
See line 60 of patientSummary.gsp

    <i class="icon-comments"><a href="#comments">Doctor's Note</a></i>

**Comment by prithi69** [comment]
Its not working, previously it was working, i think its not merged in to the master and also there is a additional Hyperlink name "Additonal Comment" is been shown, has to get deleted as it been replaced by Doctor's note.
