### ISSUE TITLE
Image carousel is not working  after pulled from master and installed in the demo/test server.

### ISSUE THREAD

**Issue by prithi69** [Intelehealth/intelehealth-openmrs-module#57]
![screenshot-2017-12-4 openmrs electronic medical record](https://user-images.githubusercontent.com/28602886/33553164-a92e1632-d91d-11e7-860d-6088235a052e.png)

**Comment by amalafrozalam** [comment]
I don't understand. You showed a screenshot of it working. Are you saying the issue is that it is not horizontal?

**Comment by prithi69** [comment]
i showed a screenshot of production server which is working, here is the screenshot.
![Uploading Screenshot-2017-12-3 OpenMRS Electronic Medical Record.png…
This module is working as i haven't pulledout it from the master and uploaded in the production server , when i was setting up the production server.

The previous screen which i have posted is the  screenshot of demo test server where i have pulled out from the master and the image carousel is not coming and also tested after you reverted all the  branch , but still it's not working.
