### ISSUE TITLE
Modify the Complaints fragment to display the text with formatting

### ISSUE THREAD

**Issue by dbarretto** [Intelehealth/intelehealth-openmrs-module#61]
Currently it displays the HTML tags. 
<img width="593" alt="screen shot 2017-12-08 at 16 40 05" src="https://user-images.githubusercontent.com/28301176/33763445-8ec53228-dc36-11e7-88df-f329f2cdbb6b.png">
It should format it properly using the HTML tags.

<b>Abdominal Pain</b>: <br/>• Site - Upper (R) - Right Hypochondrium, Upper (L) - Left Hypochondrium.<br/>• Radiation - Pain does not radiate.<br/>• Duration - since 5 Hours.<br/>• Onset - Gradual.<br/> <b>Abdominal distention</b>: <br/>• Duration - since 23 Hours.<br/>• Onset - Over few days.<br/>• Progress of abdominal distention - Swelling increases/decreases during 24-hr cycle.<br/>• Weight change (kg) - Patient has gained weight (kgs) - 8.<br/>• Appetite change - Patient’s appetite has increased.<br/>

**Comment by amalafrozalam** [comment]
This might not be possible. Further investigation required, but it might not be possible to do.

**Comment by nehav39** [comment]
Can we maybe post each complaint as a separate obs? That way at the very least each complaint can be separately displayed? 
The end user need is that the note is very difficult to read. That need has to be met.
