### ISSUE TITLE
Provide selection for type of treatment on OpenMRS i.e. Allopathy, Ayurvedic, Combination.

### ISSUE THREAD

**Issue by prithi69** [Intelehealth/intelehealth-openmrs-module#72]
need to create a separate fragment in the patient overview screen so that doctor can select which prescription they are providing whether it is allopathy, ayurvedic or combination. it will be the dropdown list of three.

**Comment by hardikk08** [comment]
![image](https://user-images.githubusercontent.com/29514954/36672387-0c4c60a4-1b25-11e8-9f91-edb601309f81.png)

User should be allowed to enter it only once right?

**Comment by prithi69** [comment]
I think, we should allowed them to enter it once,

**Comment by nehav39** [comment]
Yes, only once - so its like a radio button.

**Comment by nehav39** [comment]
Tested by Prithi.

**Comment by nehav39** [comment]
The fragment should be turned on and off.

**Comment by nehav39** [comment]
User need: Certain fragments are deployment specific and they need to be visible only for that particular deployment.

**Comment by nehav39** [comment]
Created #77
