### ISSUE TITLE
Need to create a seperate fragment in the patient dashboard screen so that doctor can provide "Follow up visit "

### ISSUE THREAD

**Issue by prithi69** [Intelehealth/intelehealth-openmrs-module#73]

**Comment by nehav39** [comment]
Relate to #433 on the Android repo

**Comment by hardikk08** [comment]
![image](https://user-images.githubusercontent.com/29514954/37084405-712d4782-2218-11e8-9fc0-f7dbde47270f.png)

Functionality similar to Treatment Type issue.
