### ISSUE TITLE
Certain fragments are deployment specific and they need to be visible only for that particular deployment.

### ISSUE THREAD

**Issue by nehav39** [Intelehealth/intelehealth-openmrs-module#77]
Turn on/off the treatment type fragment.

**Comment by hardikk08** [comment]
How about creating different apps for each deployment which can be turned on/off accordingly from the manage apps module. To do this we will have to,
1. Create a deployment specific patient summary page
2. Include required fragments for the deployment.
3. This way we won't have to manage different repos or branches and put all code into one repo and then include/exclude fragments in the patient summary page

We will have to make multiple patient dashboard apps(dep on number of deploy) and on dashboard in recent visit link, we can point it to patientSummaryHaiti.page

**Comment by nehav39** [comment]
Is there no way to turn on/off fragments on patient summary page?

**Comment by nehav39** [comment]
Apps = pages that can be managed on the manage apps page. Fragments on these app pages can't be turned on and off
Pages
Fragments

https://talk.openmrs.org/t/turning-on-off-web-app-fragments-for-client-specific-locations/17795/3

**Comment by nehav39** [comment]
Moved to new repo
