### ISSUE TITLE
Create a new header fragment to replace core apps fragment

### ISSUE THREAD

**Issue by hardikk08** [Intelehealth/intelehealth-openmrs-module#80]
Display age in years and months

**Comment by hardikk08** [comment]
@nehagoel2  Do we really want to change the header because the age displays just fine.? Its in months if age is less than a year otherwise it is rounded off to the closest I believe!

**Comment by nehav39** [comment]
I think it should be fine. Can you share screenshots of how it looks currently?

**Comment by hardikk08** [comment]
![image](https://user-images.githubusercontent.com/29514954/39415912-0f003ed4-4c66-11e8-8df3-d33bd1cb8563.png)

![image](https://user-images.githubusercontent.com/29514954/39418801-fc159706-4c79-11e8-8fa4-97ddb5d33683.png)
