### ISSUE TITLE
Images do not load from Parse server

### ISSUE THREAD

**Issue by nehav39** [Intelehealth/intelehealth-openmrs-module#81]
Sometimes, the images do not load correctly from the parse server.

Failed to load resource: : 1337/parse/classes/...
net: : ERR_CONNECTION_REFUSED

**Comment by hardikk08** [comment]
![screenshot 43](https://user-images.githubusercontent.com/29514954/39398891-43ace05e-4b32-11e8-8f5c-ed006b0fa55e.png)
![screenshot 44](https://user-images.githubusercontent.com/29514954/39398892-4403d42c-4b32-11e8-9434-3d77d7562fcb.png)
 @nehagoel2  So I just tried reproducing this issue with a dummy patient and the images are being fetched successfully. Can you tell me the patient name if it happened for a specific patient? One possible cause I can think of is that maybe the server was down.

**Comment by nehav39** [comment]
Its just on the Haiti server, and it was happening for all patients. You would need to test this on the Haiti server only. There is something going on with the Parse server config or the omod file on that one.
