### ISSUE TITLE
[RHPT] Doctor's interpretation fragment

### ISSUE THREAD

**Issue by nehav39** [Intelehealth/intelehealth-openmrs-module#84]
Fragment for doctor's interpretation of test- This is for doctor's record when he interprets the follwoing tests results. So that whenever he goes back to the patient, he doesn't have to reinterpret the test results. To be shown only on OpenMRS. 
Hypertension Package : Creatinine, Urine R/E , RBS, Total Cholesterol
ECG : 
Rhythm : Sinus / AF/ CBH/ 1 HB /Other 
Rate : 
Axis : 
SV2+RV5 = 
ST Depression : Yes/ No / Cant Interpret . 
ST Elevation : Yes / No / Cant Interpret . 
Interpretation : Normal ECG / Abnormal ECG / Cant Interteper
Blood Sugar : Normal / Abnormal / Needs HBA1c / Needs Further evaluation
ECG : Recent / old- less than 3 months / old- more than 3 month

**Comment by hardikk08** [comment]
Encounter & Concept ID's created on local server, have to be replicated on production server. 
All works fine except for a bug where suppose - 
1. Obs have been just posted and if doctor tries to delete any obs only the first deletion will work, after that no obs will get deleted.  - This might take time, it is something tricky
2. However deletion works fine after page reload and for old obs.
